services:
  postgres:
    image: postgres:16-alpine
    container_name: portfolio_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=portfolio
      - TZ=America/Sao_Paulo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portfolio -d portfolio"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - portfolio-network

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_automation
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/New_York
      - WEBHOOK_URL=https://broaden-spew-parakeet.ngrok-free.dev
      - TZ=America/Sao_Paulo
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=oeIAjOM47Kze0QmN/FCgPJoafeL/m96iDHpvdjw1UiY=
    networks:
      - portfolio-network
    volumes:
      - n8n_data:/home/node/.n8n

  portifolio-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Sao_Paulo
      - DATABASE_URL=postgres://portfolio:portfolio@postgres:5432/portfolio?sslmode=disable
      - API_KEY=${API_KEY}
      - BRAPI_TOKEN=${BRAPI_TOKEN}
      - ALPHA_KEY=${ALPHA_KEY}
      - TWELVE_DATA_KEY=${TWELVE_DATA_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - portfolio-network

volumes:
  n8n_data:
  postgres-data:

networks:
  portfolio-network:
    driver: bridge
