// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	domain "portifolio-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// AssetRepository is an autogenerated mock type for the AssetRepository type
type AssetRepository struct {
	mock.Mock
}

// DeleteByTicker provides a mock function with given fields: ticker
func (_m *AssetRepository) DeleteByTicker(ticker string) error {
	ret := _m.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByTicker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(ticker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReturnAllPortfolio provides a mock function with given fields:
func (_m *AssetRepository) ReturnAllPortfolio() ([]domain.Asset, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReturnAllPortfolio")
	}

	var r0 []domain.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Asset, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Asset); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReturnAssetPortfolio provides a mock function with given fields: ticker
func (_m *AssetRepository) ReturnAssetPortfolio(ticker string) (*domain.Asset, error) {
	ret := _m.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for ReturnAssetPortfolio")
	}

	var r0 *domain.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Asset, error)); ok {
		return rf(ticker)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Asset); ok {
		r0 = rf(ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: asset
func (_m *AssetRepository) Upsert(asset domain.Asset) error {
	ret := _m.Called(asset)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Asset) error); ok {
		r0 = rf(asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAssetRepository creates a new instance of AssetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssetRepository {
	mock := &AssetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
