// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	domain "portifolio-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// AssetRepository is an autogenerated mock type for the AssetRepository type
type AssetRepository struct {
	mock.Mock
}

// DeleteByTicker provides a mock function with given fields: userID, ticker
func (_m *AssetRepository) DeleteByTicker(userID int64, ticker string) error {
	ret := _m.Called(userID, ticker)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, string) error); ok {
		r0 = rf(userID, ticker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReturnAllPortfolio provides a mock function with given fields: userID
func (_m *AssetRepository) ReturnAllPortfolio(userID int64) ([]domain.Asset, error) {
	ret := _m.Called(userID)

	var r0 []domain.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]domain.Asset, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int64) []domain.Asset); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReturnAssetPortfolio provides a mock function with given fields: userID, ticker
func (_m *AssetRepository) ReturnAssetPortfolio(userID int64, ticker string) (*domain.Asset, error) {
	ret := _m.Called(userID, ticker)

	var r0 *domain.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string) (*domain.Asset, error)); ok {
		return rf(userID, ticker)
	}
	if rf, ok := ret.Get(0).(func(int64, string) *domain.Asset); ok {
		r0 = rf(userID, ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = rf(userID, ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: userID, asset
func (_m *AssetRepository) Upsert(userID int64, asset domain.Asset) error {
	ret := _m.Called(userID, asset)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, domain.Asset) error); ok {
		r0 = rf(userID, asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSector provides a mock function with given fields: userID, ticker, sector
func (_m *AssetRepository) UpdateSector(userID int64, ticker string, sector string) error {
	ret := _m.Called(userID, ticker, sector)

	if fn, ok := ret.Get(0).(func(int64, string, string) error); ok {
		return fn(userID, ticker, sector)
	}
	return ret.Error(0)
}

// NewAssetRepository creates a new instance of AssetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAssetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssetRepository {
	mock := &AssetRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
