// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	domain "portifolio-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MarketProvider is an autogenerated mock type for the MarketProvider type
type MarketProvider struct {
	mock.Mock
}

// GetByTickers provides a mock function with given fields: ticker
func (_m *MarketProvider) GetByTickers(ticker []domain.Asset) ([]domain.Quote, error) {
	ret := _m.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetByTickers")
	}

	var r0 []domain.Quote
	var r1 error
	if rf, ok := ret.Get(0).(func([]domain.Asset) ([]domain.Quote, error)); ok {
		return rf(ticker)
	}
	if rf, ok := ret.Get(0).(func([]domain.Asset) []domain.Quote); ok {
		r0 = rf(ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Quote)
		}
	}

	if rf, ok := ret.Get(1).(func([]domain.Asset) error); ok {
		r1 = rf(ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMarketProvider creates a new instance of MarketProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketProvider {
	mock := &MarketProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
