// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	domain "portifolio-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// PortfolioRepository is an autogenerated mock type for the PortfolioRepository type
type PortfolioRepository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *PortfolioRepository) GetAll() ([]domain.Asset, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Asset, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Asset); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPortfolioRepository creates a new instance of PortfolioRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPortfolioRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PortfolioRepository {
	mock := &PortfolioRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
