// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	domain "portifolio-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// PriceHistoryRepository is an autogenerated mock type for the PriceHistoryRepository type
type PriceHistoryRepository struct {
	mock.Mock
}

// GetLastPrice provides a mock function with given fields: ticker
func (_m *PriceHistoryRepository) GetLastPrice(ticker string) (float64, error) {
	ret := _m.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetLastPrice")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (float64, error)); ok {
		return rf(ticker)
	}
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(ticker)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: history
func (_m *PriceHistoryRepository) Save(history domain.PriceHistory) error {
	ret := _m.Called(history)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.PriceHistory) error); ok {
		r0 = rf(history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPriceHistoryRepository creates a new instance of PriceHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceHistoryRepository {
	mock := &PriceHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
